image: alpine:edge

build:
  script:
    - apk update && apk add go git make musl-dev
    - export GOPATH=/root/go
    - go get -u -v github.com/golang/dep/cmd/dep
    - mkdir -p $GOPATH/src/server
    - cp -r $CI_PROJECT_DIR/ $GOPATH/src/
    - cd $GOPATH/src/server
    - make requires
    - make
