const baseURL = `//${window.location.host}/api/v1`;

export default {
  getNews: `${baseURL}/post/getNews`,
  createNews: `${baseURL}/post/createNews`,
  updateNews: `${baseURL}/post/updateNews`,
  removeNews: `${baseURL}/post/removeNews`,
  recent: `${baseURL}/post/recent`,
  getResources: `${baseURL}/post/getResources`,
  createSuggestion: `${baseURL}/post/createSuggestion`,
  createHelpDeskTicket: `${baseURL}/post/createHelpDeskTicket`,
  getHelpDeskTickets: `${baseURL}/post/getHelpDeskTickets`,
  searchProjects: `${baseURL}/post/searchProjects`,
  searchUsers: `${baseURL}/post/searchUsers`,
  searchClients: `${baseURL}/post/searchClients`,
  searchResources: `${baseURL}/post/searchResources`,
  searchRedbook: `${baseURL}/post/searchRedbook`,
  uploadFile: `${baseURL}/post/uploadFile`,
  getOptionLocations: `${baseURL}/get/getOptionLocations`,
  getOptionTypes: `${baseURL}/get/getOptionTypes`,
  getOptionStatuss: `${baseURL}/get/getOptionStatuss`,
  getOptionDivisions: `${baseURL}/get/getOptionDivisions`,
  getOptionOffices: `${baseURL}/get/getOptionOffices`,
  getClientLocations: `${baseURL}/get/getClientLocations`,
  getOptionCategories: `${baseURL}/get/getOptionCategories`,
  getOptionClients: `${baseURL}/get/getOptionClients`,
  getOptionUsers: `${baseURL}/get/getOptionUsers`,
  fetchSuggestions: `${baseURL}/post/fetchSuggestions`,
  getClient: `${baseURL}/post/getClient`,
  getProject: `${baseURL}/post/getProject`,
  getSuggestionItemURL: `${baseURL}/post/getSuggestionItemURL`,
  getDivisions: `${baseURL}/post/getDivisions`,
  getMe: `${baseURL}/post/getMe`,
  getProjectsSiteInspectionsByProjectNumber: `${baseURL}/post/getProjectsSiteInspectionsByProjectNumber`,
  getManagerUsernameByDivisionCode: `${baseURL}/post/getManagerUsernameByDivisionCode`,
  addProject: `${baseURL}/post/createOrUpdateProject`,
  addClient: `${baseURL}/post/createOrUpdateClients`,
  addSiteInspection: `${baseURL}/post/createOrUpdateProjectSiteInspections`,
  uploadResource: `${baseURL}/post/uploadResource`,
  authRequired: `${baseURL}/post/authRequired`,
  swapCodes: `${baseURL}/post/swapCodes`,
};
