[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"
  source = "github.com/gin-gonic/gin"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  branch = "master"
  source = "github.com/jinzhu/gorm"

[[constraint]]
  name = "github.com/spf13/viper"
  branch = "master"
  source = "github.com/spf13/viper"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/gzip"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "2.5.0"
